services:
  mysql:
    image: mysql:8.0
    container_name: todo_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo_db
      MYSQL_USER: todo_user
      MYSQL_PASSWORD: todo_password
    ports:
      - "3307:3306"
    volumes:
      - todo_mysql_data:/var/lib/mysql

volumes:
  todo_mysql_data: